CREATE TABLE `LastEpochItemDB`.`Item` (
  `idItem` INT NOT NULL,
  `baseTypeName` VARCHAR(100) NULL,
  `baseDisplayName` VARCHAR(100) NULL,
  `baseTypeID` INT NULL,
  `maximumAffixes` INT NULL,
  `maxSockets` INT NULL,
  `affixEffectModifier` DECIMAL(10) NULL,
  `gridSizeX` INT NULL,
  `gridSizeY` INT NULL,
  `type` INT NULL,
  `isWeapon` INT NULL,
  `minimumDropLevel` INT NULL,
  `name` VARCHAR(100) NULL,
  `displayName` VARCHAR(100) NULL,
  `subTypeID` INT NULL,
  `levelRequirement` INT NULL,
  `cannotDrop` INT NULL,
  `itemTags` INT NULL,
  `classRequirement` INT NULL,
  `subClassRequirement` INT NULL,
  `attackRate` DECIMAL(10) NULL,
  PRIMARY KEY (`idItem`));

CREATE TABLE `LastEpochItemDB`.`Property` (
  `idProperty` INT NOT NULL,
  `propertyName` VARCHAR(100) NULL,
  `defaultAltText` VARCHAR(100) NULL,
  `roundAddedToInt` INT NULL,
  `displayAddedAsPercentage` INT NULL,
  `displayAddedAsTenthOfValue` INT NULL,
  `displayAsPercentageOf` INT NULL,
  `displayAsAddedTo` INT NULL,
  `dontDisplayPlus` INT NULL,
  `lessIsBetter` INT NULL,
  `property` INT NULL,
  `specialTag` INT NULL,
  `tags` INT NULL,
  `modType` INT NULL,
  `overrideAltText` VARCHAR(500) NULL,
  PRIMARY KEY (`idProperty`));

CREATE TABLE `LastEpochItemDB`.`Affix` (
  `idAffix` INT NOT NULL,
  `affixName` VARCHAR(100) NULL,
  `affixDisplayName` VARCHAR(100) NULL,
  `affixTitle` VARCHAR(100) NULL,
  `affixId` INT NULL,
  `levelRequirement` INT NULL,
  `rollsOn` INT NULL,
  `classSpecificity` INT NULL,
  `type` INT NULL,
  `standardAffixEffectModifier` DECIMAL(10) NULL,
  `rerollChance` DECIMAL(10) NULL,
  `weaponEffect` INT NULL,
  `group` INT NULL,
  `shardHueShift` DECIMAL(10) NULL,
  `shardSaturationModifier` DECIMAL(10) NULL,
  `canRollOn` VARCHAR(100) NULL,
  `property` INT NULL,
  `specialTag` INT NULL,
  `tags` INT NULL,
  `modifierType` INT NULL,
  `setProperty` INT NULL,
  PRIMARY KEY (`idAffix`));
